### ISSUE TITLE
您好,请问您最后的预测结果如何?

### ISSUE THREAD

**Issue by fastcode3d** [fooSynaptic/News_Stock_predict#1]
准确率如何?我也参加了这个比赛,本来想用强化学习做的,但是后来没写完..

**Comment by fooSynaptic** [comment]
> 准确率如何?我也参加了这个比赛,本来想用强化学习做的,但是后来没写完..

四次提交提交了两次，rank 9，单周最高rank3
（整什么花里胡哨的强化学习

**Comment by fastcode3d** [comment]
谢谢，我学习学习
